# Generated by Django 4.2.26 on 2025-12-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        help_text="The app this configuration belongs to",
                        max_length=100,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Configuration path, e.g., 'general/max_todos_per_user'",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="The stored configuration value",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Value",
                "verbose_name_plural": "Configuration Values",
                "ordering": ["app_label", "path"],
                "unique_together": {("app_label", "path")},
            },
        ),
    ]
