services:
  api:
    command: sh -c "python /app/src/manage.py migrate && python /app/src/manage.py runserver 0.0.0.0:8000"

  redisinsight:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped

  mail:
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1081:1080
