# Generated by Django 4.2.26 on 2025-12-28 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db_email", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="body",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="subject",
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="identifier",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="EmailTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db_email.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template Version",
                "verbose_name_plural": "Email Template Versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="emailtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="unique_template_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailtemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("template",),
                name="unique_active_version_per_template",
            ),
        ),
    ]
