# Generated by Django 4.2.26 on 2025-12-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todogroup_and_todo_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todogroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
